<?php

namespace Wexample\SymfonyUser\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;
use Wexample\SymfonyUser\Enum\PasswordResetMode;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('wexample_symfony_user');

        $treeBuilder->getRootNode()
            ->children()
                ->enumNode('password_reset')
                    ->info('How a user who forgot their password gets back in: a link to a reset form, or a magic link.')
                    ->values(array_map(static fn (PasswordResetMode $mode) => $mode->value, PasswordResetMode::cases()))
                    ->defaultValue(PasswordResetMode::TOKEN->value)
                ->end()
                ->booleanNode('reveal_account_status')
                    ->info('Tell a disabled or locked account why it cannot sign in, once its password is right. Off, every failure reads the same.')
                    ->defaultFalse()
                ->end()
                ->booleanNode('remember_locale')
                    ->info('Store on the account the language of the pages it reads, when their url carries one (symfony-translations locale_routing), so its mails follow it. Off, the application sets AbstractUser::setLocale() itself, or leaves it to the default locale.')
                    ->defaultFalse()
                ->end()
                ->booleanNode('magic_link_login')
                    ->info('Offer to sign in by magic link on the login page. Off, MagicLinkService still serves the links an application sends itself.')
                    ->defaultTrue()
                ->end()
                ->arrayNode('post_login')
                    ->info('Where a user lands once signed in, when the page they were sent away from is not theirs to open.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('routes')
                            ->info('ROLE_X: route, in order: the first role the user holds, through the hierarchy, wins.')
                            ->normalizeKeys(false)
                            ->useAttributeAsKey('role')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->scalarNode('default_route')
                            ->info('For a user holding none of them. Unset, the home page.')
                            ->defaultNull()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('impersonation')
                    ->info('Who may be impersonated. Who may impersonate is the `switch_user` key of the firewall: absent, nobody — the impersonation page and search answer 404.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('targets')
                            ->info('administered: the accounts whose roles the actor administers (the hierarchy, or `administration.manages`); any: every account, a development setting. Never oneself, a disabled or a locked account; with administered, the AccountAdministrationGuardInterface of the application are asked too.')
                            ->values(['administered', 'any'])
                            ->defaultValue('administered')
                        ->end()
                        ->integerNode('list_threshold')
                            ->info('Up to this many accounts to choose from, the page lists them all; above it, it searches.')
                            ->defaultValue(50)
                            ->min(0)
                        ->end()
                        ->booleanNode('require_intent')
                            ->info('A switch must come from the impersonation form: a bare `?_switch_user=` link, sent to an administrator, switches nobody. Off for an application keeping links of its own.')
                            ->defaultTrue()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('session')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('idle_lifetime')
                            ->info('Seconds a signed-in session survives with nobody asking anything of it: past them, the next request signs the account out and lands on the login page. 0, the default, never expires one — the session lives as long as its cookie. Requests under /_, which a script makes and not a reader, are held to the delay without refreshing it: a page left open polling does not keep a session alive.')
                            ->defaultValue(0)
                            ->min(0)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('password')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('refuse_leaked')
                            ->info('Refuse a password found in a data breach, beside the strength SetPasswordForm already asks. Needs symfony/http-client: each check asks api.pwnedpasswords.com for the hashes sharing the first five characters of its own, never the password. Off by default — it is an outbound call on a page that must work, and an application on a closed network has nobody to ask.')
                            ->defaultFalse()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('activation')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('link_lifetime')
                            ->info('Seconds the link of an activation mail works: an invitation is read later than a reset.')
                            ->defaultValue(604800)
                            ->min(3600)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('request_limit')
                    ->info('Password reset and magic link requests, per hour. Past a limit, the answer reads the same and nothing is sent.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('per_identifier')->defaultValue(3)->min(1)->end()
                        ->integerNode('per_ip')->defaultValue(20)->min(1)->end()
                    ->end()
                ->end()
                ->arrayNode('administration')
                    ->info('The rules AccountAdministrationService applies to every change an administrator makes to an account.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('page_role')
                            ->info('The role opening the account administration pages symfony-user-ds draws (`/accounts`). Unset — the default —, nobody has them: the pages and the actions answer 404, as the impersonation page does without `switch_user`. Set it only where administering accounts is the intent; what each administrator may then reach is still the rules below.')
                            ->defaultNull()
                        ->end()
                        ->arrayNode('protected_roles')
                            ->info('Roles never left without an active holder: the last one cannot be deactivated, locked, or lose the role.')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('manages')
                            ->info('Which roles each role administers, ROLE_X: [ROLE_A, ROLE_B], apart from the hierarchy and granting no security right. Unset, an actor administers the roles they reach.')
                            ->normalizeKeys(false)
                            ->useAttributeAsKey('role')
                            ->arrayPrototype()->scalarPrototype()->end()->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('role_email_domains')
                            ->info('Roles held only by an email of these domains, ROLE_X: [example.com]. Checked on every flush of an account.')
                            ->normalizeKeys(false)
                            ->useAttributeAsKey('role')
                            ->arrayPrototype()->scalarPrototype()->end()->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('exclusive_roles')
                            ->info('Roles never held together, ROLE_X: [ROLE_A, ROLE_B] — either way round. Checked on every flush of an account.')
                            ->normalizeKeys(false)
                            ->useAttributeAsKey('role')
                            ->arrayPrototype()->scalarPrototype()->end()->end()
                            ->defaultValue([])
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('terms')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('version')
                            ->info('The version of the terms of use in force. Set, every signed-in user must have accepted it before reaching anything else; changing it asks everyone again, at their next request.')
                            ->defaultNull()
                        ->end()
                        ->scalarNode('text_route')
                            ->info('The route of the page holding the text of the terms, owned by the application.')
                            ->defaultNull()
                        ->end()
                        ->scalarNode('text_template')
                            ->info('A template holding the text of the terms, owned by the application: shown on the acceptance page itself, in a box read through before accepting. Include the same template on the text_route page, so the text is written in one place.')
                            ->defaultNull()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('two_factor')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('pending_lifetime')
                            ->info('Seconds a correct password waits for its second factor. Past it, the sign-in starts over from the password.')
                            ->defaultValue(600)
                            ->min(60)
                        ->end()
                        ->booleanNode('required')
                            ->info('Every sign-in asks a second factor — magic link and the login after a reset included —, and no account is exempt.')
                            ->defaultFalse()
                        ->end()
                        ->arrayNode('app_required_roles')
                            ->info('Roles that must use an authenticator app: signed in by email code until it is set up, held on its setup page meanwhile, never allowed to turn it off.')
                            // Replaced, not merged: an environment emptying the list
                            // (`[]` under when@test) must empty it.
                            ->performNoDeepMerging()
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
